// <auto-generated />
using System;
using Energy_Monitoring_System.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Energy_Monitoring_System.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250821025445_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Energy_Monitoring_System.Domain.Models.Leitura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Corrente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergiaAtivaDireta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergiaAtivaReversa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FatorPotencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Frequencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MedidorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PotenciaAtiva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PotenciaReativa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tensao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MedidorId", "Timestamp");

                    b.ToTable("Leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
